#!/usr/bin/env bash
# vi: ft=sh
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd master
docker kill jenkins-master
docker rm -v jenkins-master
./build
docker run --name jenkins-master -v $PWD/.test:/var/jenkins -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 -p 50000:50000 -d docker-jenkins
popd



